// <auto-generated />
namespace SuperShopManagementSystem.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Purchase_ForaignKey_Solution : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Purchase_ForaignKey_Solution));
        
        string IMigrationMetadata.Id
        {
            get { return "201802041120383_Purchase_ForaignKey_Solution"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
